apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eventflow

resources:
  - namespace.yaml
  - postgres.yaml
  - kafka-cluster.yaml
  - order-service.yaml
  - payment-service.yaml
  - inventory-service.yaml
  - notification-service.yaml
  - networkpolicy.yaml
  - web-bff.yaml
  - secrets.yaml
  - api-gateway.yaml
  - tenant-service.yaml

commonLabels:
  app.kubernetes.io/part-of: eventflow
